### ISSUE TITLE
Is it possible to save the HTML Code from an URL?

### ISSUE THREAD

**Issue by niklasxbr** [jasonmerino/react-native-simple-store#11]
Is there a way to save html code of an URL? 
So that I can request this HTML-Code from store.get() and to view it in a WebView?

**Comment by jasonmerino** [comment]
I'm sure there is a way to do that. How is the HTML defined? Separate HTML file? Template literal?

**Comment by niklasxbr** [comment]
It is just a normal HTML Website, like Google or anything Else.
It contains Images an normal DIV-Elements.

Von meinem iPhone gesendet

**Comment by niklasxbr** [comment]
It is just a normal HTML Website, like Google or bettet dribbble.com.
It contains Images and normal Elements like DIVs or something like that.

**Comment by jasonmerino** [comment]
So you are looking to request HTML from a URL from your app and save that to AsyncStorage?

**Comment by niklasxbr** [comment]
Yes that is right!

**Comment by jasonmerino** [comment]
Okay, I just played around with this enough to get it to work. Here's what I came up with. 

```js
import store from 'react-native-simple-store';

fetch('http://google.com')
	// return the res.text() to get the body of the request
	.then((res) => res.text())
	.then((body) => {
		store
			.save('google', body)
			// just for verification get the value for the key 'google' in simple store
			.then(() => store.get('google'))
			.then((value) => {
				// value is the markup for the google page
			});
	});
```

**Comment by jasonmerino** [comment]
Closing this now, but if you have more questions feel free to comment again.
