### ISSUE TITLE
How do you check if a key: value already exists on a store?

### ISSUE THREAD

**Issue by Dcl1** [jasonmerino/react-native-simple-store#13]
nvm solved it.

**Comment by sbefort** [comment]
LOL thanks for not posting the solution for everyone else.

**Comment by Dcl1** [comment]
THANKS SHAUN! I actually realized a closer look at the original example shows how to check whether or not the .get returns a null. I believe. I didn't write anything because I thought it was obvious mistake, but I'll remember for the future.

**Comment by jasonmerino** [comment]
To check to see if a key has a value associated with it you would need to do something like this.

simpleStore.get('key').then((value) => {
  if (value !== null) {
    // key exists
  } else {
    // key does not exist
  }
});

I'm working on an additional function on the simple store called keys which will get all keys in AsyncStorage but haven't been able to publish it yet. Hopefully soon.

**Comment by jasonmerino** [comment]
Closing this issue since it's a question. Feel free to continue commenting if more help is needed.
