### ISSUE TITLE
Update NPM

### ISSUE THREAD

**Issue by headlessme** [jasonmerino/react-native-simple-store#16]
Could you publish the latest version to NPM?

**Comment by jasonmerino** [comment]
Yeah, I'm working on that. Probably have it out by the end of the week.

**Comment by jasonmerino** [comment]
I've been taking some time to update the tests and add some examples, but the full examples will have to wait until after the new version goes out.

**Comment by jasonmerino** [comment]
Okay, just released 1.1.0. Adds ability to get multiple keys, save multiple keys, list all keys, and deep merges objects in `.update()`.
