### ISSUE TITLE
I can’t make it work on a real iOS device

### ISSUE THREAD

**Issue by sdebacker** [jasonmerino/react-native-simple-store#23]
Hello,

Currently I can use this library with the simulator by running react-native run-ios, but when I open the xcode project and run the app on a real device (debug or release), the store doesn’t work anymore. Is there something I’m not aware of ? I’m using react-native 0.39.2.

**Comment by jasonmerino** [comment]
Hey @sdebacker,

Sorry for the delay in my reply. There is nothing special that you should need to do to get this to work on an actual device. Would you mind trying to use [AsyncStorage](http://facebook.github.io/react-native/releases/0.39/docs/asyncstorage.html#asyncstorage) directly and see if you still have the same problems?

**Comment by sdebacker** [comment]
I don't know what was wrong, but, now it works. Thanks for your reply.

**Comment by jasonmerino** [comment]
Glad to hear it. :) Happy coding.
