### ISSUE TITLE
Compatibility with react-native 0.40

### ISSUE THREAD

**Issue by alfonsodev** [jasonmerino/react-native-simple-store#24]
Since [December version](https://github.com/facebook/react-native/releases/tag/v0.40.0) 
react-native team introduce a breaking change that affects third party modules.  
I'm quoting here the message from the release notes. It would be great if you could upgrade the package 🎉   Thanks ! 

## iOS native headers moved

This change affects all native modules and application code on iOS that refer to react native .h files
After e1577df, Native code on iOS must refer to headers out of the react namespace. Previously the following would work:
```
#import "RCTUtils.h"
```
But now all headers have been moved:
```
#import <React/RCTUtils.h>
```
This means that all iOS native libraries need a major version bump for RN 0.40. We attempt to minimize changes of this magnitude, and we apologize for any inconvenience caused.

**EDIT** : Consider also using the macro suggested in the following article, to support 0.40 *and* keep compatibility with previous versions. 
https://medium.com/@thisismissem/how-to-upgrade-react-native-modules-in-a-backwards-compatible-manner-a5b5c48d590c#.vh7nbtd26

**Comment by alfonsodev** [comment]
I'm closing this issue,  
sorry but this is not needed, this module is just javascript.  
I've included it by mistake in a list of dependencies that actually need to move headers.

**Comment by jasonmerino** [comment]
No worries @alfonsodev. I figured that much, but hadn't had the time to go check it out for myself. Thanks double checking and closing. :)

Have a good one!
