### ISSUE TITLE
store.save(key, value) stopped working

### ISSUE THREAD

**Issue by y2k-shubham** [jasonmerino/react-native-simple-store#37]
- All of a sudden, store.save(key, value) has broken down.
- It was functioning properly (verified by store.get(key)) until I (once) executed store.delete(key)

---

- While I can verify that data is being saved by invoking store.get(key) immediately after store.save(key, value), the data won't persist after re-launching the app (in fact I'm not sure after how long the data vanishes)
- Furthermore, I didn't install any new packages (or modified any existing ones), which could be blamed for it

---

After (obviously) removing store.delete(key) call, I tried the following without luck:
- uninstalling app on iOS simulator before re-installing
- restarting packager with --reset-cache
- rebooting my laptop (facepalm!)
- taking fresh clone of the (private) repo and re-installing all packages

Configuration:
- RN v0.46.4
- react-native-simple-store v1.3.0

**Comment by jasonmerino** [comment]
@y2k-shubham thanks for the replication steps and reporting this issue. Can you post some code that you are seeing this issue with? It can be the different pieces of your code as it sounds like the bug is happening after some time.

Thanks!

**Comment by jasonmerino** [comment]
Going to close this issue due to lack of activity. @y2k-shubham if this is still an issue for you comment back and we can reopen it and do some more diagnosing.
