### ISSUE TITLE
RN simple store is breaking my mocha tests

### ISSUE THREAD

**Issue by GantMan** [jasonmerino/react-native-simple-store#4]
Whenever I test an object that has RN simple store I get the following:

```
/Users/gantman/Documents/Projects/rn/trackops-mobile/node_modules/react-native-simple-store/index.js:3
var {
    ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Module._extensions..js (module.js:432:10)
```
here's a screencap, if that helps at all...

![image](https://cloud.githubusercontent.com/assets/997157/11449286/0bfe891a-9535-11e5-87f2-eb161d3eeb39.png)

I'm using mocha and chai.

**Comment by jasonmerino** [comment]
Hey! Sorry about the late reply. Which version of Babel are you using?

**Comment by GantMan** [comment]
Babel 6 - Technically "babel": "^6.0.15",

**Comment by jasonmerino** [comment]
According to this [Babel page](https://babeljs.io/docs/setup/#mocha) 

> Pre-6.x, Babel enabled certain transformations by default. However, Babel 6.x does not ship with any transformations enabled.

Have you 

```bash
npm install babel-preset-es2015
```

And added

```json
{
  "presets": ["es2015"]
}
```

to your `.babelrc` file?

**Comment by GantMan** [comment]
sorry, I must be missing something.  Bringing in es2015 causes a new error.
![image](https://cloud.githubusercontent.com/assets/997157/11507152/504ddd4c-9818-11e5-81f2-c0eb6cef14ec.png)

**Comment by jasonmerino** [comment]
Okay, I've attempted a change on my side. Can you change your `package.json` to install the babel6 branch from Github directly, rather than NPM. Test that out and see if it works.

The entry for `dependencies.react-native-simple-store` in your `package.json` should look like this:

```JSON
"react-native-simple-store": "git@github.com:jasonmerino/react-native-simple-store.git#babel6"
```

After making that change run:

```bash
npm install
```

Let me know if that fixes your issue.

**Comment by GantMan** [comment]
I got further, but now I'm stuck at this:
![image](https://cloud.githubusercontent.com/assets/997157/11517426/fe0e1146-984e-11e5-9819-29b1878f834d.png)

Which appears to be a real sticking point: http://stackoverflow.com/questions/32212201/get-mocha-working-with-react-native-errors-w-requiring-addons

It's so funny, my tests run fine until I import the wrong library.   I'm really starting to wonder if this testing solution will work.  I'm going to attempt to mock these native components, but I'm afraid I won't be able to make this work.  I'll let you know, but thanks for the update, it definitely got further.

**Comment by jasonmerino** [comment]
Interesting. Yeah, mocking these out may work. Good luck. Let me know if you get it working without any more changes on my side.

**Comment by jasonmerino** [comment]
@GantMan I'm going to close this one out. Please comment to reopen it if there is something I can do to help out with this.

**Comment by GantMan** [comment]
@jasonmerino - your branch does at least fix the babel issue.

I suggest you merge it.   I'm still fighting to get other testing features working.  But I didn't want this result to go to waste.

**Comment by GantMan** [comment]
ok got past my issues, but 100% depending on your babel branch.  Please merge that to master :)

cheers!

**Comment by GantMan** [comment]
@jasonmerino - please add this to master.   I'm 100% working on the branch and it's good to go.

**Comment by jasonmerino** [comment]
@GantMan sorry about not getting back to you earlier. I've learned a little more about how babel interacts with code recently and I'd like to attempt to fix this one a different way. I'll reopen this issue. I'd love your help trying to test this out to get it fixed with babel and the new Ecmascript syntax. I'll probably be able to get to some fixes this week sometime.

**Comment by GantMan** [comment]
happy to help however I can

**Comment by tomauty** [comment]
+1

**Comment by GantMan** [comment]
any updates?  I'm still locked to your branch.

**Comment by jasonmerino** [comment]
@GantMan sorry about the delay here. It's turned into a bit more of a change than I thought. Ends up I'm going to be releasing a transpiled version of the package over NPM which will basically amount to what you're working off in that other branch I set up. Bear with me for a bit and I'll let you know when the new version is out.

**Comment by jasonmerino** [comment]
@GantMan once again I must apologize for not getting this out earlier... But! I think I have a fix in master for what you were seeing. When you have a moment can you install the version from master and make sure that it doesn't break your tests?

```
"react-native-simple-store": "git@github.com:jasonmerino/react-native-simple-store.git#master"
```

**Comment by jasonmerino** [comment]
@GantMan I'm going to close this out for now. I've published version 1.0.1 which is standard ES5 stuff.

Comment back if you still have trouble after upgrading to the newest version and I'll re-open this and get back to work. :)

**Comment by GantMan** [comment]
Sorry for the delay.   Switched from branch to master and everything worked!  Cheers!

**Comment by jasonmerino** [comment]
No worries! Glad to hear it's working. :)
