### ISSUE TITLE
store.delete delete by ID

### ISSUE THREAD

**Issue by shiroze** [jasonmerino/react-native-simple-store#48]
if I have key array struktur like this

`'Bookmark' = {[
         ID : 1,
         isBooked: true
],[
         ID : 3,
         isBooked: true
]}`

I want delete / remove ID : 1, how to do it ?

**Comment by jasonmerino** [comment]
Assuming you had a structure like this:

```js
const Bookmark = [{
  ID: 1,
  isBooked: true
}, {
  ID: 3,
  isBooked: true
}];
```

And that was stored in simple store you would do something like this to delete it and save it back to simple store.

```js
async function deleteBookmarkById(id) {
  const bookmark = await store.get('bookmark');
  const newBookmarks = bookmark.filter((b) => b.ID !== id);
  await store.save('bookmark', newBookmarks);
  return newBookmarks;
}
```
