### ISSUE TITLE
Why update and save

### ISSUE THREAD

**Issue by mauron85** [jasonmerino/react-native-simple-store#5]
Why there is update and save methods? They basically do the same thing in key value db.

**Comment by jasonmerino** [comment]
There's a slight difference between `.save` and `.update`. Save just saves whatever you give it. If there is something there already it will overwrite that value with the given one. Update will pull whatever value is there and if it's an object it will merge the two objects.

Minor difference, but I favored the different function over passing a flag to `.save`.

**Comment by jasonmerino** [comment]
Closing this out as it's not really an issue, just a question. @mauron85 if you have any more questions you can hit me up on Twtiter [@jasonmerino](http://twitter.com/jasonmerino) or Discord.
