### ISSUE TITLE
Unable to resolve module `@react-native-community/async-storage`

### ISSUE THREAD

**Issue by maryasdk** [jasonmerino/react-native-simple-store#57]
Hi,
I just updated to react-native 0.59.8 from 0.58.
I updated as well to react-native-simple-storage from 1.3.0 to 2.0.0 to remove the warning regarding async-storage.

I am getting the following error on runtime:
Unable to resolve module `@react-native-community/async-storage` from `/Users/maryasadek/RN/Washmen/node_modules/react-native-simple-store/dist/index.js`: Module `@react-native-community/async-storage` does not exist in the Haste module map

I tried resetting node modules, and the cache, but it did not help.
![image](https://user-images.githubusercontent.com/31656696/59042452-271fce80-8883-11e9-8f77-b40d6d04c5d9.png)

**Comment by jasonmerino** [comment]
Hey @maryasdk,

Sorry to hear you are having trouble. Did you run the command to link the new async-storage module in your project?

```react-native link @react-native-community/async-storage```

There are some installation instructions [in the README](https://github.com/jasonmerino/react-native-simple-store#installation) calling this out.

If you have run link, or run it and still have trouble, please feel free to comment back here. :)

**Comment by maryasdk** [comment]
Linking fails with the message: Failed to get dependency config.

Below is the verbose error message. 
Note: that I do not use async storage in my app independently of simple-store

![image](https://user-images.githubusercontent.com/31656696/59090596-dc9b6200-8915-11e9-9fc0-f58002c9059f.png)

**Comment by duzliang** [comment]
@maryasdk you should install the `@react-native-community/async-storage` before link
when I install the `@react-native-community/async-storage`, it's works to me

**Comment by maryasdk** [comment]
@duzliang I did not try to do so. I thought that it should be downloaded by the simple-store library since it is a dependency of the library itself. I guess I'll do it ur way, if there isnt an update to fix the issue soon. Thanks

**Comment by jasonmerino** [comment]
It looks like `@react-native-community/async-storage` was only added as a devDependency. :/ 

I'll look into adding that as a normal dependency and see if I can add in the linking step as a `postinstall` script so that part of the setup isn't needed anymore.

**Comment by maryasdk** [comment]
Okay thanks @jasonmerino waiting for your update
