### ISSUE TITLE
TypeError: Cannot read property 'cache' of undefined

### ISSUE THREAD

**Issue by younes200** [jasonmerino/react-native-simple-store#58]
I updated  react-native-simple-storage from 1.3.0 to 2.0.0 to remove the warning regarding async-storage.
But it fails with :
```
error: bundling failed: TypeError: Cannot read property 'cache' of undefined
    at module.exports (/Project/node_modules/react-native-simple-store/babel.config.js:2:6)
```
After removing this line https://github.com/jasonmerino/react-native-simple-store/blob/fe17187e811572fa2a1645ae084747e58360f4e6/babel.config.js#L2
it works fine.

A [PR](https://github.com/jasonmerino/react-native-simple-store/pull/59) is available it makes sens to you.

I Am using `"@babel/core": "^7.4.4"`

Any idea ?
Thanks

**Comment by joelfsreis** [comment]
Hi, I am having this issue as well... Removing the line `api.cache(true)` make it work again. Will this be fixed soon? Cheers!
