### ISSUE TITLE
Outdated bookstore

### ISSUE THREAD

**Issue by skantus** [jasonmerino/react-native-simple-store#61]
It would be nice to create a new tag with the latest changes since it is quite outdated from the main branch.

## Last tag _7 jun 2017_

![2019-07-03_1534](https://user-images.githubusercontent.com/4986411/60595982-52290f80-9da8-11e9-86d0-99fc2d50d3cb.png)

Thanks for help with this plugin.

@jasonmerino @oas

**Comment by jasonmerino** [comment]
I just pushed all the most recent tags I have on this machine. Seems like I'm missing v2.0.0 but I've switched machines recently, so I think that one may be gone as far as this git repo knows. 😏
