### ISSUE TITLE
What is it?

### ISSUE THREAD

**Issue by QShengW** [jasonmerino/react-native-simple-store#62]
Unhandled JS Exception: TypeError: TypeError: (0 , _reactNativeSimpleStore.default) is not a function

**Comment by jasonmerino** [comment]
I'm not sure what your question is. Could you provide a little more context about the problem you're having?

**Comment by jasonmerino** [comment]
I'm going to close this since it's been inactive for a while. If this is still an issue for you and you would like to provide more detail, please open another issue.
